//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// test_client.login.rc에서 사용되고 있습니다.
//
#define IDD_TEST_CLIENT_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAIN                   130
#define IDC_EDIT_PORT                   1000
#define IDC_BUTTON_CONNECT1             1001
#define IDC_STATIC_CONNECTION_C         1002
#define IDC_RICHEDIT21                  1003
#define IDC_STATIC_CONNECTION_C2        1003
#define IDC_EDIT_ADDRESS                1004
#define IDC_STATIC_FOOTER               1005
#define IDC_EDIT_CONNECTION_INTERVAL    1006
#define IDC_EDIT_MESSAGE_SEND_COUNT_BEFORE_DISCONNECT 1007
#define IDC_BUTTON_DISCONNECT           1008
#define IDC_BUTTON_POOL                 1009
#define IDC_BUTTON_CONNECT100           1010
#define IDC_EDIT_MESSAGE_LENGTH         1011
#define IDC_BUTTON_THREAD               1012
#define IDC_BUTTON_CLOSE                1013
#define IDC_EDIT_CHANNEL_ID_MIN         1014
#define IDC_BUTTON_CONNECT10            1015
#define IDC_EDIT_MESSAGE_INVERVAL       1016
#define IDC_EDIT_CONNECTION_MIN         1017
#define IDC_CHECK_CONNECT_TEST_STARTSTOP 1018
#define IDC_EDIT_CONNECTION_MAX         1019
#define IDC_BUTTON_CONNECT              1020
#define IDC_BUTTON_DISCONNECT_ALL       1021
#define IDC_EDIT_CONNECT_PER_SEC        1022
#define IDC_EDIT_DISCONNECT_PER_SEC     1023
#define IDC_EDIT_CHANNEL_ID_MAX         1024
#define IDC_EDIT_CHANNEL_ID_SELECTED    1025
#define IDC_BUTTON_CLOSE_ALL            1026
#define IDC_EDIT_CONNECT_TIMES          1027
#define IDC_EDIT_ACCOUNT_ID_MIN         1028
#define IDC_EDIT_ACCOUNT_NAME_INDEX_MIN 1028
#define IDC_EDIT_ACCOUNT_ID_MAX         1029
#define IDC_EDIT_ACCOUNT_NAME_INDEX_MAX 1029
#define IDC_EDIT_ACCOUNT_ID_SELECTED    1030
#define IDC_EDIT_ACCOUNT_ID_MAX2        1031
#define IDC_EDIT_ACCOUNT_NAME           1031
#define IDC_STATIC_FRAME_SETTING        1045
#define IDC_STATIC_FRAME_TRAFFIC        1046
#define IDC_STATIC_FRAME_CONNECTION_INFO 1047
#define IDC_STATIC_FRAME_CHANNEL_SERVER 1048
#define IDC_CHECK_MESSAGE_SEND_COUNT_BEFORE_DISCONNECT 1056
#define IDC_CHECK_MESSAGE_SEND_TEST     1057
#define IDC_CHECK_CONNECTION_TEST       1058
#define IDC_CHECK_ENTER_CHANNEL_TEST    1059
#define IDC_RADIO_CHANNEL_ID_SELECTED   1060
#define IDC_RADIO_CHANNEL_ID_RANDOM     1061
#define IDC_STATIC_CONNECTION_INTERVAL  1062
#define IDC_STATIC_CONNECTION_MIN       1063
#define IDC_STATIC_CONNECTION_MAX       1064
#define IDC_STATIC_CHANNEL_ID_MIN       1065
#define IDC_STATIC_CHANNEL_ID_MAX       1066
#define IDC_STATIC_MESSAGE_LENGTH       1067
#define IDC_STATIC_MESSAGE_INVERVAL     1068
#define IDC_STATIC_MESSAGE_INVERVAL_TAIL 1069
#define IDC_CHECK_CONNECTION_DISCONNECT 1070
#define IDC_STATIC_CONNECTION_INTERVAL_TAIL 1071
#define IDC_CHECK_MESSAGE_SEND_COUNT_BEFORE_DISCONNECT_TAIL 1072
#define IDC_STATIC_CONNECTION_MIN2      1073
#define IDC_STATIC_CONNECTION_B         1073
#define IDC_STATIC_CONNECTION_MIN3      1074
#define IDC_STATIC_CONNECTION_A         1074
#define IDC_STATIC_CHANNEL_ID_MIN2      1075
#define IDC_CHECK_MAKE_NEW_MEMBER_DATA  1076
#define ID_SYSTEM_EXIT                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
